package presentation.web;

import java.io.IOException;
import java.sql.Connection;

import java.sql.SQLException;
import java.sql.Statement;


import data.ArticleDAO;
import data.DAOFactory;
import jakarta.servlet.ServletConfig;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import transfer.Article;

/**
 * Servlet implementation class DaoTest
 */
@WebServlet("/TestDao")
public class TestDao extends HttpServlet {
	
	private static final long serialVersionUID = 1L;

       
	private ArticleDAO articleDAO;
    /**
     * @see HttpServlet#HttpServlet()
     */
    public TestDao() {
        super();
         
    }
    
    @Override
	public void init(ServletConfig config) throws ServletException {
		// TODO Auto-generated method stub
		super.init(config);
		
		Statement stmt = null;

    
    	Connection conn = null;        	
        try
        {
        	conn = (Connection) getServletContext().getAttribute("connection");        	stmt = conn.createStatement();
        	stmt.execute("drop table if exists articles");
        	stmt.execute("create table articles (\r\n"
        			+ "  id                            bigint generated by default as identity not null,\r\n"
        			+ "  name                          varchar(255) not null,\r\n"
        			+ "  price                         float not null,\r\n"
        			+ "  quantity                		int not null,\r\n"
        			+ "  constraint pk_articles primary key (id)\r\n"
        			+ ")");
        }
        catch(SQLException e)
        {
        	System.out.println(e.getMessage());
        }
		articleDAO = DAOFactory.getArticleDAO();
		
        
        articleDAO.add(new Article(0,"TestArtikel01",10,3));
        
        articleDAO.add(new Article(0,"TestArtikel02",20,5));
      
        articleDAO.add(new Article(0,"TestArtikel03",30,7));
        
        articleDAO.add(new Article(0,"TestArtikel04",40,4));
        
        articleDAO.add(new Article(0,"TestArtikel05",50,2));
        
        articleDAO.add(new Article(0,"TestArtikel06",60,6));
      
        
        
       
	}


	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		response.getWriter().println("-------------------------------------------------");
		response.getWriter().println("Alle Artikel:");
		response.getWriter().println("-------------------------------------------------");
		
		for (Article a : articleDAO.getAll()) {
			response.getWriter().println(a.getId());
			response.getWriter().println(a.getName());
			response.getWriter().println(a.getPrice());
			response.getWriter().println(a.getQuantity());
			response.getWriter().println();
		}
		response.getWriter().println("-------------------------------------------------");
		response.getWriter().println("Artikel mit ID 3");
		response.getWriter().println("-------------------------------------------------");
		Article a = articleDAO.get(3);
		
		response.getWriter().println(a.getId());
		response.getWriter().println(a.getName());
		response.getWriter().println(a.getPrice());
		response.getWriter().println(a.getQuantity());
		response.getWriter().println();
		
		response.getWriter().println("-------------------------------------------------");
		response.getWriter().println("Artikel mit ID 3 aktualisieren");
		response.getWriter().println("-------------------------------------------------");
		a = articleDAO.get(3);
		a.setName(a.getName()+"Update");
		a.setQuantity(a.getQuantity() + 2);
		a.setPrice(a.getPrice() + 1);
		articleDAO.update(a);
		a = articleDAO.get(3);
		
		response.getWriter().println(a.getId());
		response.getWriter().println(a.getName());
		response.getWriter().println(a.getPrice());
		response.getWriter().println(a.getQuantity());
		response.getWriter().println();
		response.getWriter().println("-------------------------------------------------");
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}

}
